#' Function to compute mahalanobis distance between weighted mean and fks mean
#'
#' This function aims to evaluate whether the estimated smoothing distribution is close to the real smoothing
#' distribution computed by FKS for Gaussian linear models by evaluating the distance between them
#'
#' @param x Particles generated by the algorithm
#' @param w Weights of particles
#' @param fks.obj Fks information of the linear Gaussian model
#'
#' @return A plot contains the distance of the whole time scale
#' @export 
#'
compute_dKS <- function(x, w, fks.obj){
  d <-  ncol(as.matrix(x[1,,]))
  dist <- vector()
  for(t in 1:Time){
    w_ <- normalise_weights_in_log_space(w[t,])[[1]]
    if(d == 1){
      weighted_mean <- sum(w_*x[t,,])
    }else{
      weighted_mean <- colSums(w_*x[t,,])
    }

    fks_mean <- fks.obj$ahatt[,t]
    fks_cov <- fks.obj$Vt[,,t]

    dist[t] <- mahalanobis(weighted_mean, fks_mean, fks_cov)  #squared d? Not divide?
  }

  plot(dist)
  return(dist)
}
