#' Function to run the iterated APF
#'
#' @param model Information of the model
#' @param data Information of the required data
#' @param Napf Number of particles users would like to generate
#'
#' @return A list contains:
#' X_apf is the particles generated by iAPF at the time of the upper boundary of the given block
#' w_apf is the weights generated by iAPF at the time of the upper boundary of the given block
#' psi_pa is the parameters of the distribution psi the algorithm finally choose
#' Z_apf is the estimated normalising constant
#' ancestors is all the indices of ancestors of particles during the algorithm
#'
#' @export
#'
run_iAPF_rolling <- function(model, data, Napf){
  obs <- data$obs
  past <- data$past
  X_apf <- past[[1]]
  w_apf <- past[[2]]
  
  k <- model$parameters$k
  Time <- nrow(obs)
  d = ncol(obs)
  
  run_block <- data$run_block
  b_s <- run_block[1]
  b_e <- run_block[2]
  
  l = 1
  Z_apf <- vector()
  N[l] = Napf
  
  if(l <= k ){
    
    #receive filtering particles X_apf for psi
    psi_pa <- learn_psi(X_apf[b_s:b_e,,, drop = FALSE], obs[b_s:b_e,, drop = FALSE],
                        model, log_likelihoods)
    
    
    l <- l+1
  }
  
  
  return(list(X_apf = X_apf[dim(X_apf)[1],,], w_apf = w_apf[nrow(w_apf),], psi_pa, Z_apf = Z_apf[l], ancestors))
}
